# docker-compose.yml for Neo4j Database
# This configuration sets up a Neo4j database with necessary environment variables,
# volumes for data persistence, and a health check. It also includes an initialization
# service to run custom Cypher scripts upon startup.

# try image: neo4j:4.0.7-enterprise

services:
  neo4j:
    image: "neo4j:2025.11"
    container_name: neo4j
    restart: unless-stopped
    # The ports that will be accessible from outside the container - HTTP (7474) and Bolt (7687).
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    networks:
      - naglfar-network
    environment:
      # Authentication
      # - NEO4J_AUTH=neo4j/naglfar123
      # Memory Configuration
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_memory_pagecache_size=512M
      - NEO4J_server_memory_heap_initial__size=512M
      - NEO4J_server_memory_heap_max__size=1G
      # Database Configuration
      - NEO4J_db_tx__log_rotation_retention__policy=100M size
      # APOC Configuration (Advanced Procedures)
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      # Disable authentication for development purposes
      - NEO4J_dbms_security_auth__enabled=false
      # plugin "bloom" may require licence acceptance
      - NEO4J_PLUGINS=["apoc", "graph-data-science", "bloom", "genai"]
      # download plugins automatically
      - NEO4J_dbms_directories_plugins=/plugins
      - NEO4J_dbms_security_procedures_unrestricted="apoc.*,gds.*,bloom.*,genai.*"
      # Logging
      # - NEO4J_server_logs_debug_level=INFO
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    healthcheck:
      test: [ "CMD-SHELL", "echo RETURN 1 | cypher-shell -a http://localhost:7474 -u neo4j -p 123 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

    # healthcheck:
    #   test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 40s

  # neo4j-init:
  #   image: "neo4j:2025.11"
  #   container_name: neo4j-init
  #   networks:
  #     - naglfar-network
  #   depends_on:
  #     neo4j:
  #       condition: service_healthy
  #   volumes:
  #     - ./init-schema.cypher:/init/init-schema.cypher:ro
  #     - ./init.sh:/init/init.sh:ro
  #   entrypoint: ["/bin/bash", "/init/init.sh"]
  #   restart: "no"

networks:
  naglfar-network:
    driver: bridge
    name: naglfar-network

volumes:
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  neo4j-import:
    driver: local
  neo4j-plugins:
    driver: local
