services:
  api-gateway:
    image: "traefik:v3.6"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - naglfar-network
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--log.level=INFO"
      - "--metrics.prometheus=true"
      # - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.addserviceslabels=true"
      - "--metrics.prometheus.addentrypointslabels=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  naglfar-validation:
    build:
      context: ../services/naglfar-validation
      dockerfile: Dockerfile
    container_name: naglfar-validation
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - SIGNATURE_KEY="0064283c-e357-11f0-b060-6e04387dcc74"
    restart: unless-stopped
    networks:
    - naglfar-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apivone.rule=Host(`api.local`)"
      - "traefik.http.routers.apivone.entrypoints=web"
      - "traefik.http.routers.apivone.service=apivone"
      - "traefik.http.services.apivone.loadbalancer.server.port=8000"

  protected-service-eu:
    build:
      context: ../services/book-store
      dockerfile: Dockerfile
    container_name: book-store-eu
    ports:
      - "8081:8000"
    environment:
      - REGION=europe
    restart: unless-stopped
    networks:
    - naglfar-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.book-store-eu.rule=Host(`book-store-eu.local`)"
      - "traefik.http.routers.book-store-eu.entrypoints=web"
      - "traefik.http.routers.book-store-eu.service=book-store-eu"
      - "traefik.http.services.book-store-eu.loadbalancer.server.port=8000"

  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8082:8000"
    environment:
      - REGION=europe
      - SIGNATURE_KEY="0064283c-e357-11f0-b060-6e04387dcc74"
    restart: unless-stopped
    networks:
    - naglfar-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=Host(`auth-service.local`)"
      - "traefik.http.routers.auth-service.entrypoints=web"
      - "traefik.http.routers.auth-service.service=auth-service"
      - "traefik.http.services.auth-service.loadbalancer.server.port=8000"

  # whoami:
  #   image: "traefik/whoami"
  #   container_name: whoami
  #   restart: unless-stopped
  #   networks:
  #     - naglfar-network
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
  #     - "traefik.http.routers.whoami.entrypoints=web"

networks:
  naglfar-network:
    driver: bridge
    name: naglfar-network
  # proxy:
  #   external: true
  #   driver: bridge
