services:
  api-gateway:
    image: "traefik:v3.6"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - naglfar-network
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--log.level=INFO"
      - "--metrics.prometheus=true"
      # - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.addserviceslabels=true"
      - "--metrics.prometheus.addentrypointslabels=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  naglfar-validation:
    build:
      context: ../services/naglfar-validation
      dockerfile: Dockerfile
    container_name: naglfar-validation
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - SIGNATURE_KEY="0064283c-e357-11f0-b060-6e04387dcc74"
      - Redis__ConnectionString=redis:6379
    restart: unless-stopped
    networks:
    - naglfar-network
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apivone.rule=Host(`api.local`)"
      - "traefik.http.routers.apivone.entrypoints=web"
      - "traefik.http.routers.apivone.service=apivone"
      - "traefik.http.services.apivone.loadbalancer.server.port=8000"

  protected-service-eu:
    build:
      context: ../services/book-store
      dockerfile: Dockerfile
    container_name: book-store-eu
    ports:
      - "8081:8000"
    environment:
      - REGION=europe
    restart: unless-stopped
    networks:
    - naglfar-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.book-store-eu.rule=Host(`book-store-eu.local`)"
      - "traefik.http.routers.book-store-eu.entrypoints=web"
      - "traefik.http.routers.book-store-eu.service=book-store-eu"
      - "traefik.http.services.book-store-eu.loadbalancer.server.port=8000"

  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8082:8000"
    environment:
      - REGION=europe
      - SIGNATURE_KEY="0064283c-e357-11f0-b060-6e04387dcc74"
    restart: unless-stopped
    networks:
    - naglfar-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=Host(`auth-service.local`)"
      - "traefik.http.routers.auth-service.entrypoints=web"
      - "traefik.http.routers.auth-service.service=auth-service"
      - "traefik.http.services.auth-service.loadbalancer.server.port=8000"

  redis:
    image: "redis:8"
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - naglfar-network
    # Weâ€™ve enabled persistence in Redis by using the append-only file (AOF) feature.
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    # healthcheck:
    #   test:
    #     - CMD
    #     - redis-cli
    #     - ping
    #   retries: 3
    #   timeout: 5s

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "5540:5540"
    networks:
      - naglfar-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDISINSIGHT_HOST=0.0.0.0
      - REDISINSIGHT_ACCEPT_LICENSE=true  # Accept EULA and Privacy Settings
    volumes:
      - redisinsight-data:/data
      - ./redis-insight/databases.json:/data/databases/databases.json:ro
    # depends_on:
    #   redis:
    #     condition: service_healthy

networks:
  naglfar-network:
    driver: bridge
    name: naglfar-network
  # proxy:
  #   external: true
  #   driver: bridge

volumes:
  redis-data:
    driver: local
  redisinsight-data:
    driver: local
